### ISSUE TITLE
Run in MacOS

### ISSUE THREAD

**Issue by EstebanFuentealba** [Milk-Cool/flippulator#1]
Hello, excellent work. I tried running the Flippulator, but I encountered the following error messages. What should I do?

<img width="1680" alt="Captura de pantalla 2023-10-13 a la(s) 16 28 45" src="https://github.com/Milk-Cool/flippulator/assets/442927/969200ba-18fb-4312-8dd0-3f6d8c29e49a">

**Comment by Milk-Cool** [comment]
Hello! Sorry for late answer, I somehow didn't notice your issue.
This project does not officially support macOS (only Linux), however I think it might actually work. Try cloning using git with the flag `--recursive` and see if it works!

**Comment by Milk-Cool** [comment]
closing, no answer
