### ISSUE TITLE
Flippulator android && IOS

### ISSUE THREAD

**Issue by Lilspooky-cyber** [Milk-Cool/flippulator#6]
I need some help on programing firmware ![Screenshot_20240818_105916_WhatsApp.jpg](https://github.com/user-attachments/assets/0fb4aff0-1fe6-4ec2-ad0b-781be3fd715b)

**Comment by Milk-Cool** [comment]
Sorry, this project is not maintained anymore. I should probably archive it. 

And also iOS and Android support was never planned
